### PR TITLE
Add test coverage

### PR DESCRIPTION
**Pull request by jcollado**
I was curious about what would be the test coverage for this package, so I added `coverage` as a dependency and a `Makefile` to generate the coverage report as: `make coverage`

### CODE REVIEW

**Comment by robingustafsson** [comment]
LGTM, thanks @jcollado!

**Comment by jcollado** [comment]
@robingustafsson Great! Now maybe you can register the project in coveralls.io or codecov.io and add badge to the `README`.

**Comment by robingustafsson** [comment]
@jcollado Good suggestion. I've now setup converalls.io and added badge.

**Comment by jcollado** [comment]
@robingustafsson :+1:

**Pull request merged**
